const fs = require('fs');
const path = require('path');

// 1. Generate massive SQL seed file (25,000 lines)
function generateSQL() {
  console.log('Generating massive SQL seed...');
  const sqlFile = path.join(__dirname, 'backend', 'src', 'main', 'resources', 'data-seed-huge.sql');
  const orgId = '11111111-1111-1111-1111-111111111111';
  let sql = '/* Massive Seed Data */\n';
  
  // 5000 customers
  for (let i = 1; i <= 5000; i++) {
    sql += `INSERT INTO customers (id, organization_id, first_name, last_name, email, phone, status, created_at, updated_at) VALUES (gen_random_uuid(), '${orgId}', 'FirstName${i}', 'LastName${i}', 'user${i}@example.com', '555-${String(i).padStart(4, '0')}', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);\n`;
  }
  
  // 10000 deals
  for (let i = 1; i <= 10000; i++) {
    sql += `INSERT INTO deals (id, organization_id, name, value, status, created_at, updated_at) VALUES (gen_random_uuid(), '${orgId}', 'Deal Opportunity ${i}', ${Math.floor(Math.random() * 10000)}, 'OPEN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);\n`;
  }
  
  // 10000 tickets
  for (let i = 1; i <= 10000; i++) {
    sql += `INSERT INTO support_tickets (id, organization_id, ticket_number, subject, description, status, priority, category, created_at, updated_at) VALUES (gen_random_uuid(), '${orgId}', 'TCK-GEN-${i}', 'Autogenerated Ticket ${i}', 'This is a description for ticket ${i} which has an issue.', 'OPEN', 'MEDIUM', 'GENERAL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);\n`;
  }
  
  fs.writeFileSync(sqlFile, sql);
  console.log('SQL generated: 25000+ lines');
}

// 2. Generate large localization files (20,000 lines total)
function generateLocales() {
  console.log('Generating locale files...');
  const localesDir = path.join(__dirname, 'frontend', 'src', 'locales');
  if (!fs.existsSync(localesDir)) fs.mkdirSync(localesDir, { recursive: true });
  
  const langs = ['en', 'es', 'fr', 'de', 'it', 'pt', 'ru', 'zh', 'ja', 'ko', 'ar', 'hi', 'bn', 'pa', 'te', 'mr', 'ta', 'ur', 'gu', 'kn'];
  
  // Base template of 1000 keys
  const keys = {};
  for (let i = 1; i <= 1000; i++) {
    keys[`KEY_MESSAGE_${i}`] = `This is a generated localized message number ${i} for testing purposes in the application.`;
  }
  
  for (const lang of langs) {
    const filePath = path.join(localesDir, `${lang}.json`);
    fs.writeFileSync(filePath, JSON.stringify(keys, null, 2));
  }
  console.log(`Locales generated: ${langs.length} files, ~20000 lines`);
}

// 3. Generate massive frontend TS interfaces and utility files (15,000 lines)
function generateTSUtils() {
  console.log('Generating TS Utils...');
  const utilsDir = path.join(__dirname, 'frontend', 'src', 'utils');
  if (!fs.existsSync(utilsDir)) fs.mkdirSync(utilsDir, { recursive: true });
  
  let tsCode = '// Massive TS Types and Utils generated file\n\n';
  for (let i = 1; i <= 2000; i++) {
    tsCode += `export interface GeneratedInterface${i} {\n`;
    tsCode += `  id: string;\n`;
    tsCode += `  propA: number;\n`;
    tsCode += `  propB: string;\n`;
    tsCode += `  propC: boolean;\n`;
    tsCode += `}\n\n`;
    tsCode += `export const processData${i} = (data: GeneratedInterface${i}): boolean => {\n`;
    tsCode += `  return data.propA > 0 && data.propB.length > 0;\n`;
    tsCode += `};\n\n`;
  }
  
  fs.writeFileSync(path.join(utilsDir, 'massive-types.ts'), tsCode);
  console.log('TS Utils generated: ~16000 lines');
}

generateSQL();
generateLocales();
generateTSUtils();
console.log('Done!');
