import { test, expect } from '@playwright/test';

test.describe('SmartCommunication E2E Flow', () => {
  
  test.beforeEach(async ({ page }) => {
    // Navigate to the base URL
    await page.goto('http://localhost:3000');
  });

  test('should load the dashboard and verify key metrics', async ({ page }) => {
    // Check if the title is correct or at least loads
    await expect(page).toHaveTitle(/SmartCommunication CRM/);

    // Navigate to Analytics Dashboard
    await page.goto('http://localhost:3000/analytics');
    
    // Verify headers
    await expect(page.locator('h1')).toContainText('Analytics Dashboard');
    
    // Verify some metrics exist
    await expect(page.getByText('Total Revenue (YTD)')).toBeVisible();
    await expect(page.getByText('Active Customers')).toBeVisible();
  });

  test('should create a new support ticket', async ({ page }) => {
    await page.goto('http://localhost:3000/support');
    
    await expect(page.locator('h1')).toContainText('Help Desk');
    
    // Click New Ticket button
    await page.click('button:has-text("New Ticket")');
    
    // Fill out the form
    await page.fill('input[type="email"]', 'testuser@example.com');
    
    // Select the first text input inside the modal (Customer Name)
    await page.locator('.fixed.inset-0 input[type="text"]').first().fill('Test User');
    
    // Select the second text input inside the modal (Subject)
    const subjectInput = page.locator('.fixed.inset-0 input[type="text"]').nth(1);
    await subjectInput.fill('Playwright Test Subject');
    
    await page.fill('textarea', 'This is an automated test ticket description generated by Playwright.');
    
    // Submit
    await page.click('button:has-text("Create Ticket")');
    
    // Verify the modal closes
    await expect(page.locator('.fixed.inset-0')).toBeHidden();
  });

  test('should navigate to Document Hub and verify upload button', async ({ page }) => {
    await page.goto('http://localhost:3000/documents');
    
    await expect(page.locator('h1')).toContainText('Document Hub');
    await expect(page.locator('button:has-text("Upload File")')).toBeVisible();
    
    await page.click('button:has-text("Upload File")');
    await expect(page.locator('h2:has-text("Upload File")')).toBeVisible();
  });

  test('should navigate to Team Members and open Invite modal', async ({ page }) => {
    await page.goto('http://localhost:3000/team');
    
    await expect(page.locator('h1')).toContainText('Team Members');
    await expect(page.locator('button:has-text("Invite User")')).toBeVisible();
    
    await page.click('button:has-text("Invite User")');
    await expect(page.locator('h2:has-text("Invite Team Member")')).toBeVisible();
  });

  test('should navigate to Settings and switch tabs', async ({ page }) => {
    await page.goto('http://localhost:3000/settings');
    
    await expect(page.locator('h1')).toContainText('Settings');
    
    // Default is Personal Information
    await expect(page.locator('h2')).toContainText('Personal Information');
    
    // Click Organization tab
    await page.click('button:has-text("Organization")');
    await expect(page.locator('h2').first()).toContainText('Organization Settings');
    
    // Click Security tab
    await page.click('button:has-text("Security")');
    await expect(page.locator('h2').first()).toContainText('Security Settings');
    
    // Click Billing & Plan tab
    await page.click('button:has-text("Billing & Plan")');
    await expect(page.locator('h2').first()).toContainText('Billing & Plan');
  });

});
